name: Markdown Lint

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  markdown_lint:
    permissions:
      contents: read
    name: Lint Markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Markdown Lint
        uses: ruzickap/action-my-markdown-linter@abb659d26eea70aee77a555bd057b9c45ddd3332
        with:
          debug: true
          config_file: .github/.markdownlint.yml
          exclude: |
            .changeset/
            .github/
            CODE_OF_CONDUCT.md
            LICENSE
            CHANGELOG.md
