name: Markdown Lint

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  markdown_lint:
    permissions:
      contents: read
    name: Lint Markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Markdown Lint
        uses: ruzickap/action-my-markdown-linter@5e4b49fb65d856a021b96ad7f799cc3bde9af91e
        with:
          debug: true
          config_file: .github/.markdownlint.yml
          exclude: |
            .changeset/
            .github/
            CODE_OF_CONDUCT.md
            LICENSE
            CHANGELOG.md
